### ISSUE TITLE
Can't load data into Tableau

### ISSUE THREAD

**Issue by pratio** [tagyoureit/InfluxDB_WDC#1]
```
Error creating object for class TableInfo. The input data for one of the contained objects is invalid. Error creating object for class ColumnInfo. Error: Unknown Data Type.
```
When i run the connector locally and check the console, i can see the data is returned in response but it doesn't seem to load in Tableau
```
{"results":[{"statement_id":0,"series":[{"name":"system","columns":["fieldKey","fieldType"],"values":[["load1","float"],["load15","float"],["load5","float"],["n_cpus","integer"],["n_users","integer"],["uptime","integer"],["uptime_format","string"]]}]}]}

```

**Comment by tagyoureit** [comment]
Try it now.  I just had float datatype in my database.  The problem was with the dataTypeEnum.  Tableau wants "int" and Influx gives "integer" so just did a little mapping to correct that.  Thanks for pointing this out.

**Comment by tagyoureit** [comment]
Closing this for now.  Please re-open if you are still having issues.
