### ISSUE TITLE
Can't change to https

### ISSUE THREAD

**Issue by seanhoughton** [tagyoureit/InfluxDB_WDC#10]
I'm using Chrome Version 68.0.3440.106 (Official Build) (64-bit) and I'm unable to change the source from "http" to "https". When I alter the setting in the dropdown it just returns to "http". I can work around the problem by hardcoding it in the source.

Thanks for the adapter, it's awesome once I apply the workaround!

**Comment by tagyoureit** [comment]
I just pushed up a fix.  Can you please test it out?  
thx,
Tag
