### ISSUE TITLE
Unknown Data Type

### ISSUE THREAD

**Issue by BGraco** [tagyoureit/InfluxDB_WDC#12]
Versions:
Running on Build 16299 Windows 10
2.0.2 of InfluxDB_WDC, running on my local computer
2018.3.3 Tableau Desktop

Running on Ubuntu 18..04
1.7.3 of influxDB
node.js v11.10.0

I am able to connect to my influxDB server and pick a database for import, but when I hit submit I get the error below immediately. I am not aggregating data, and are trying to import as all rows. 
![image](https://user-images.githubusercontent.com/10716284/53251549-87975100-3682-11e9-8757-acf74c5bf972.png)

Even trying the default _internal database results in the same failure.

Debugging I can see that InfluxDB_WDC.js dies at line 305. Evidently Tableau decided debuggers should not be able to export data, so here is a screen shot of the json object.

![image](https://user-images.githubusercontent.com/10716284/53261097-cb955080-3698-11e9-81c3-eafadb3cd5ef.png)

**Comment by tagyoureit** [comment]
If you run a custom SQL query like "select * from cq limit 20" (from _internal) do you get results back?  See picture...

![2019-02-22_11-42-18](https://user-images.githubusercontent.com/1646840/53267046-49585c80-3697-11e9-93c8-f43905768539.jpeg)

**Comment by BGraco** [comment]
I realized when I saw your connector window mine looked quite different. I installed InfluxDB_WDC via npm and it seems npm has older versions of the files. Grabbing the file directly from GIT resolved the issue!

**Comment by tagyoureit** [comment]
Ahhh, got it.  I forgot/didn't realize it was published up to NPM.  I updated the package there so anyone else should be able to get the correct version.
