### ISSUE TITLE
External links to be white-listed in tableau server 

### ISSUE THREAD

**Issue by BhanupriyaSi** [tagyoureit/InfluxDB_WDC#16]
Hi,

While using this WDC on Tableau server, I experienced an issue. Data is not getting refreshed using this WDC. We have whitelisted this WDC but still issue is not resolved yet. Could please share all the external links related to this WDC, so that we can whitelist all of them on our tableau server.

 I look forward to your response asap.

Thanks
Bhanupriya

**Comment by tagyoureit** [comment]
The only files hosted are here on Github: https://github.com/tagyoureit/InfluxDB_WDC.  There isn't anything else that should need to be whitelisted.  

You may want to check the [debugging](https://tableau.github.io/webdataconnector/docs/wdc_debugging.html) steps and see if you can discover any issues.  Alternatively, you can download the files and host them yourself inside your firewall.  

Finally, you might want to open a support case to see if there is anything in the server logs that can identify the problem.

**Comment by BhanupriyaSi** [comment]
Hi,

Support case is already opened and they have already checked server logs multiple times. But the issue is not getting resolved. Attaching the snip of error. Please check.

![Error](https://user-images.githubusercontent.com/47021419/64159701-42858000-ce58-11e9-9a9e-ba681b14c75c.PNG)

**Comment by tagyoureit** [comment]
Bhanupriya, I don't think there is anything I can do to help.  I suggest you setup a webserver internal to your organization and host these files there so you don't have any network issues.
