### ISSUE TITLE
Using WDC with InfluxDB Cloud

### ISSUE THREAD

**Issue by ajohnson1117** [tagyoureit/InfluxDB_WDC#24]
Does this support InfluxDB Cloud? I attempted to use this by using my cloud credentials, but receive the following error.

![image](https://user-images.githubusercontent.com/69642060/212748342-904603e7-b4d1-4806-b847-c0c79633a791.png)

**Comment by tagyoureit** [comment]
Unfortunately, I'm not actively maintaining this now.  I may be able to get back to it at some point, but can't commit to that at this moment.

I would suggest you check the chrome developer tools to see exactly what error is happening.  You might be able to host this locally but you will definitely run into issues if you try to load it from the Github pages and then connect to InfluxDB Cloud.
