### ISSUE TITLE
Invalid input Id (spaces)

### ISSUE THREAD

**Issue by gaddman** [tagyoureit/InfluxDB_WDC#3]
I'm unable to load data into Tableau from a table, getting the following error:

`Error creating object for class TableInfo. The input data for one of the contained objects is invalid. The input Id 'mean_Primary software image' is invalid. The Id must contain only letters, numbers or underscores.`

I haven't tested yet, but I'm guessing this due to the spaces in the fieldname. Spaces are valid for InfluxDB, is this something that would need to be fixed in the WDC or is it a Tableau limitation?

**Comment by tagyoureit** [comment]
Hi... yes, you are absolutely right.  In fact, I need to deal with " , = as well as spaces.  I just pushed up a beta version of the code that I test with the following [escape characters](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/#special-characters-and-keywords).

Can you test with the [beta version](https://tagyoureit.github.io/InfluxDB_WDC/InfluxDB_escape_char_fix.html) and let me know if this works for you?  If so, I'll upgrade the permanent url and make this version 1.2.

**Comment by gaddman** [comment]
Thanks, but no better unfortunately.
I've tried using the [WDC debugger](https://tableau.github.io/webdataconnector/docs/wdc_debugging#debugging-tableau) to shed some light, but that hasn't been very helpful. The last console entry is the 'Calling init function in phase: gatherData' and I never hit a breakpoint in the getData function (at [line 356](https://github.com/tagyoureit/InfluxDB_WDC/blob/358846c0bccdbdb461a948e4ba7460235f8db5e4/InfluxDB_WDC_escape_char_fix.js#L356)). Same behaviour on the previous version mind you.
Note that in my example it's a field name which contains spaces, not a tag name.

I'll keep digging, maybe the WDC simulator will help with diagnosis.

**Comment by tagyoureit** [comment]
**Update: I just added "1.2 BETA" text to the version I pushed at the bottom of the page.  This should help identify it easier.**

Hi,

I tested with the following and it works.  Are you sure you pointed to the beta version link?  All three of the following fields worked for me.

```
> show field keys
name: wea ther
fieldKey    fieldType
--------    ---------
temperature float

name: wea,ther
fieldKey    fieldType
--------    ---------
temperature float

name: weather
fieldKey    fieldType
--------    ---------
temp=rature float
temperature float
```

The Simulator can be kind of tricky.  You should hit the debug point when you click "Fetch Table Data" one of the tables.  This is when the WDC actually gets the data.

Here are some tips for debugging:
* When you click the "Start Interactive Phase" button you will get a popup window.  If you show your console for that window you will be able to debug the interactive phase.
* When that window closes and you return to the main simulator page, you'll open a different console window and be able to debug the getData phase.  As I pointed out above, it sounds like you aren't actually fetching the data yet.

**Comment by tagyoureit** [comment]
If you still have issues, can you post your measurements/tags/fields and some sample data?  Then I can test it out locally.

**Comment by gaddman** [comment]
Hi,
I managed to get the simulator working and I can see the problem now. The [str.replace function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) only replaces the first instance of the matching character, and in some of my field names I have multiple special characters, including a few not captured in your list. I ended up changing the replaceSpecialChars function to this:
```javascript
return str.replace(/ /g,'_').replace(/\-/g,'_').replace(/"/g, '_doublequote_').replace(/,/g,'_comma_').replace(/=/g,'_equal_').replace(/\//g,'_fslash_');
```
before realising that was going to get pretty unwieldy, and settled on this:
```javascript
  return str.replace(/[^A-Za-z0-9_]/g,'_');
```
I can see that risks duplicating fields/tags if different special chars are both replaced with underscores but that seems like a reasonable tradeoff for me.
thanks,
chris

**Comment by tagyoureit** [comment]
Ah, brilliant!  That's interesting you have "special" field keys that aren't listed by Influx.  I've started to make a separate pass to fix this (I'd like to further minimize the opportunity to duplicate field/tags), but now I'm seeing that if I have a measurement name like `wea,therwea=therwea=therwea\-therwea"ther` it isn't getting encoded/escaped properly per for both internet standards and Influx encoding/escaping rules.

**Comment by tagyoureit** [comment]
Ok, I just pushed up some changes.  This is how I am naming the TableauID field now...
```
  var newStr = str.replace(/ /g,'_')
  .replace(/"/g, '_doublequote_')
  .replace(/,/g,'_comma_')
  .replace(/=/g,'_equal_')
  .replace(/\//g,'_fslash_')
  .replace(/-/g,'_dash_')
  .replace(/[^A-Za-z0-9_]/g,'_');
```

So, I try to capture the known characters and then use your catch-all to find any other characters.  This should minimize the number of exact duplicates after replacing the characters.

The harder part was actually figuring out what I can send in the query string part of the URL.  Some characters I could send directly but others needed to be escaped with a backslash.  

On another note, it looks Influx is now on Version 1.3.1.  Need to see what's new...

**Comment by gaddman** [comment]
Works like a charm, thanks!

**Comment by tagyoureit** [comment]
That's great!  I updated the main html page to the latest version (1.2) today.  I'll leave up the `beta version` and then wipe it out when I update to the next version, but you should switch to the main pages so the temporary ones don't disappear on you.  I'll close this for now, but reopen it if you have any issues.  Thanks for the help in figuring this out.
