### ISSUE TITLE
"The web data connector returned invalid data"

### ISSUE THREAD

**Issue by APenketh** [tagyoureit/InfluxDB_WDC#6]
Hi, 

Trying to Query data and receive the following error. Could you help provide some ways of debugging?

`An error occurred while communicating with the data source.

The web data connector returned invalid data.
Error creating object for class TableInfo. The input data for one of the contained objects is invalid. Either invalid data are present or required fields are empty for class ColumnInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true),
(Name : 'dataType', Type : QString, IsRequired : true),
(Name : 'alias', Type : QString, IsRequired : false),
(Name : 'hidden', Type : bool, IsRequired : false),
(Name : 'description', Type : QString, IsRequired : false),
(Name : 'isPrimaryKey', Type : bool, IsRequired : false),
(Name : 'foreignKey', Type : QVariantMap, IsRequired : false),
(Name : 'columnRole', Type : QString, IsRequired : false),
(Name : 'columnType', Type : QString, IsRequired : false),
(Name : 'aggType', Type : QString, IsRequired : false),
(Name : 'geoRole', Type : QString, IsRequired : false),
(Name : 'defaultFormat', Type : QVariantMap, IsRequired : false),
(Name : 'filterable', Type : bool, IsRequired : false)
}
`

Thanks in advance.

**Comment by tagyoureit** [comment]
Hi, you can find these [instructions for debugging](http://tableau.github.io/webdataconnector/docs/wdc_debugging).  Or if you have a sample of the data I can debug it for you.

It looks like you might have a field name with invalid characters that I haven't yet caught, or maybe some missing data.  It would need more investigation to be sure.

**Comment by APenketh** [comment]
Hi. Thanks for getting back to me, I will attempt to see if I can do some debugging myself and report back with the results.

**Comment by tagyoureit** [comment]
This might be similar to #7.  I tried to catch all of the special characters, but if I missed some or there are duplicates with series names it could be an issue.

**Comment by levent2014** [comment]
> Hi,
> 
> Trying to Query data and receive the following error. Could you help provide some ways of debugging?
> 
> `An error occurred while communicating with the data source.
> 
> The web data connector returned invalid data.
> Error creating object for class TableInfo. The input data for one of the contained objects is invalid. Either invalid data are present or required fields are empty for class ColumnInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true),
> (Name : 'dataType', Type : QString, IsRequired : true),
> (Name : 'alias', Type : QString, IsRequired : false),
> (Name : 'hidden', Type : bool, IsRequired : false),
> (Name : 'description', Type : QString, IsRequired : false),
> (Name : 'isPrimaryKey', Type : bool, IsRequired : false),
> (Name : 'foreignKey', Type : QVariantMap, IsRequired : false),
> (Name : 'columnRole', Type : QString, IsRequired : false),
> (Name : 'columnType', Type : QString, IsRequired : false),
> (Name : 'aggType', Type : QString, IsRequired : false),
> (Name : 'geoRole', Type : QString, IsRequired : false),
> (Name : 'defaultFormat', Type : QVariantMap, IsRequired : false),
> (Name : 'filterable', Type : bool, IsRequired : false)
> }
> `
> 
> Thanks in advance.

I just came across the same problem. It turned out to be a little bug that query type is set to be 'simple' in InfluxDB_WDC.js while 3rd option 'Query Type is 'All Rows' by default in InfluxDB.html.  The author uses 'on' function to change query type but it will not work if users do nothing on selecting. So just set query type   to 'all' in consistence with the page.

**Comment by tagyoureit** [comment]
D'oh!  Thanks.  Missed that one.  Good debugging @levent2014.  I just fixed this in the code.

**Comment by revanna7226** [comment]
> Hi,
> 
> Trying to Query data and receive the following error. Could you help provide some ways of debugging?
> 
> `An error occurred while communicating with the data source.
> 
> The web data connector returned invalid data.
> Error creating object for class TableInfo. The input data for one of the contained objects is invalid. Either invalid data are present or required fields are empty for class ColumnInfo. Required fields and respective data types are: { (Name : 'id', Type : QString, IsRequired : true),
> (Name : 'dataType', Type : QString, IsRequired : true),
> (Name : 'alias', Type : QString, IsRequired : false),
> (Name : 'hidden', Type : bool, IsRequired : false),
> (Name : 'description', Type : QString, IsRequired : false),
> (Name : 'isPrimaryKey', Type : bool, IsRequired : false),
> (Name : 'foreignKey', Type : QVariantMap, IsRequired : false),
> (Name : 'columnRole', Type : QString, IsRequired : false),
> (Name : 'columnType', Type : QString, IsRequired : false),
> (Name : 'aggType', Type : QString, IsRequired : false),
> (Name : 'geoRole', Type : QString, IsRequired : false),
> (Name : 'defaultFormat', Type : QVariantMap, IsRequired : false),
> (Name : 'filterable', Type : bool, IsRequired : false)
> }
> `
> 
> Thanks in advance.

Hi,

I'm also facing same issue on Tableau Desktop.

But,The WDC working fine and retrieving data on the WDC Simulator(http://tableau.github.io/webdataconnector/Simulator/). I wondering why it is not working on Tableau Desktop.

Thank you in advance,

Regards,
Revanna

**Comment by tagyoureit** [comment]
The simulator is a completely different engine than Tableau Desktop/Server and so sometimes you don't get the same error messages.  I would suggest to follow the [2019.4](https://tableau.github.io/webdataconnector/docs/wdc_webengine.html) debug instructions and see if you can get more accurate error messages as they come from Tableau Desktop itself.
