### ISSUE TITLE
The web data connector returned invalid data - invalid character in Id

### ISSUE THREAD

**Issue by robertlabrie** [tagyoureit/InfluxDB_WDC#7]
Hi,

Error creating object for class TableInfo. The input data for one of the contained objects is invalid. The input Id 'response.code' is invalid. The Id must contain only letters, numbers or underscores.

We have periods in a number of our column names, `response.code` is one of them. Any chance for a fix?

**Comment by robertlabrie** [comment]
Probably just another regex here: https://github.com/tagyoureit/InfluxDB_WDC/blob/gh-pages/InfluxDB_WDC.js#L30

**Comment by tagyoureit** [comment]
I pushed this up.  Let me know if it solves the issue.

**Comment by robertlabrie** [comment]
Cool, I'll try it later ... I tried that fix locally though and it didn't help. I'm using Tableau Desktop 2018-2 so it might be a version thing. I had to add this to getSchema
```
        for (j = 0; j < json.schema.length; j++)
        {
            for ( i = 0; i < json.schema[j]['columns'].length; i++)
            {
                json.schema[j]['columns'][i]['id'] = replaceSpecialChars_forTableau_ID(json.schema[j]['columns'][i]['id']);
            }
        }
        schemaCallback(json.schema);
```

**Comment by robertlabrie** [comment]
To be clear, I found out we're using 10.3 in prod as well so I'll switch to that version in my lab

**Comment by tagyoureit** [comment]
Ok, I think I see what's going on.  I'm not replacing the characters in the column names in a couple places.
Can you try the following.
[Line 288](https://github.com/tagyoureit/InfluxDB_WDC/blob/gh-pages/InfluxDB_WDC.js#L288): `id: replaceSpecialChars_forTableau_ID(el),`
[Line 299](https://github.com/tagyoureit/InfluxDB_WDC/blob/gh-pages/InfluxDB_WDC.js#L299): `id: replaceSpecialChars_forTableau_ID(el),`

This should do at the init phase what you figured out at the schemaCallback phase.  I'm going out of town for a week, but if this works I'll push it up when I get back.

**Comment by robertlabrie** [comment]
Ok, so that seemed to do it. The thing is now all the column IDs look like this `_dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot_`

Happened with the table id too. I had to change line 688 to `dataString += encodeURIComponent(json.customSqlSplit[table.tableInfo.alias]);` to get data back with my custom SQL. 


```
table: 
{…}
​_dataCallbackFn: function ()
​appendRows: function ()
​filterColumnId: ""
​filterValues: Array []
​incrementValue: ""
​isJoinFiltered: false
​tableInfo: {…}
​​alias: "http.response"
​​columns: Array(24) [ {…}, {…}, {…}, … ]
​​id: "_dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot__dot_"
​​<prototype>: Object { … }
​<prototype>: Object { _appendRows: _appendRows(), … }
```

**Comment by robertlabrie** [comment]
I think you want this: `.replace(/\./g, '_dot_')`

**Comment by robertlabrie** [comment]
Ok, yeah, that did it, looking good now. Still needed to use the tableInfo.alias instead of .id but it's not all _dot_ anymore. Had to escape the `.` b/c regex.

Thanks!

**Comment by tagyoureit** [comment]
Silly mistake!  But nice catch.  I accepted your PR. Thanks.
